import { fs, path } from "./cep/node";
import { csi, evalTS } from "./utils/bolt";
import { findGitRoot } from "./providers/shared";

const ACTION_DIR = ".session";
const ACTION_FILE = "ai-action.jsx";
const META_FILE = "ai-action.json";

export interface AiActionState {
  scriptPath: string;
  metaPath: string;
  summary: string;
  updatedAt: string;
}

export interface ParsedAiActionResponse {
  displayText: string;
  scriptContent?: string;
  runImmediately: boolean;
  multipleBlocks?: boolean;
}

function resolveRepoRoot(projectRoot?: string): string | null {
  const repoRoot = findGitRoot(projectRoot);
  if (repoRoot) return repoRoot;
  if (projectRoot) return projectRoot;
  return null;
}

function resolveExampleRoot(projectRoot?: string): string | null {
  try {
    const extensionRoot = csi.getSystemPath("extension");
    if (extensionRoot) {
      return path.resolve(extensionRoot, "..", "..");
    }
  } catch {}

  const repoRoot = resolveRepoRoot(projectRoot);
  if (!repoRoot) return null;

  return path.join(repoRoot, "examples", "ai-chat");
}

function resolveAiActionPaths(projectRoot?: string) {
  const exampleRoot = resolveExampleRoot(projectRoot);
  if (!exampleRoot) return null;

  const actionDir = path.join(exampleRoot, ACTION_DIR);
  return {
    actionDir,
    scriptPath: path.join(actionDir, ACTION_FILE),
    metaPath: path.join(actionDir, META_FILE),
  };
}

function ensureActionDir(actionDir: string) {
  fs.mkdirSync(actionDir, { recursive: true });
}

function buildScriptHeader(summary: string): string {
  return [
    "// AI Action",
    "// Temporary session script generated by the AI chat panel.",
    "// This file is overwritten frequently and should not be committed.",
    "// Summary: " + summary,
    "",
  ].join("\n");
}

function toSummary(displayText: string): string {
  const firstLine = displayText
    .split("\n")
    .map((line) => line.trim())
    .find(Boolean);

  return firstLine || "AI Action ready";
}

export function parseAiActionResponse(content: string): ParsedAiActionResponse {
  const AI_ACTION_REGEX = /<ai-action(?:\s+run="(true|false)")?>([\s\S]*?)<\/ai-action>/gi;
  const matches: RegExpExecArray[] = [];
  let m: RegExpExecArray | null;
  while ((m = AI_ACTION_REGEX.exec(content)) !== null) {
    matches.push(m);
  }

  if (matches.length === 0) {
    return {
      displayText: content.trim(),
      runImmediately: false,
    };
  }

  const first = matches[0];
  const runImmediately = (first[1] || "").toLowerCase() === "true";
  const scriptContent = first[2].trim();

  // Remove all ai-action blocks from the display text
  const displayText = content
    .replace(/<ai-action(?:\s+run="(?:true|false)")?>([\s\S]*?)<\/ai-action>/gi, "")
    .trim();

  return {
    displayText: displayText || "AI Action updated.",
    scriptContent: scriptContent || undefined,
    runImmediately,
    multipleBlocks: matches.length > 1,
  };
}

export function clearAiAction(projectRoot?: string): string | null {
  if (!fs) return null;

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) return null;

  try {
    if (fs.existsSync(paths.scriptPath)) {
      fs.unlinkSync(paths.scriptPath);
    }
    if (fs.existsSync(paths.metaPath)) {
      fs.unlinkSync(paths.metaPath);
    }
  } catch (err: any) {
    return err?.message || String(err);
  }

  return null;
}

export function hasAiAction(projectRoot?: string): boolean {
  if (!fs) return false;

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) return false;

  return fs.existsSync(paths.scriptPath);
}

export function saveAiAction(
  projectRoot: string | undefined,
  scriptContent: string,
  displayText: string
): AiActionState {
  if (!fs) {
    throw new Error("Node.js filesystem access is unavailable.");
  }

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) {
    throw new Error("AI Action storage could not be resolved from the extension path.");
  }

  ensureActionDir(paths.actionDir);

  const summary = toSummary(displayText);
  const scriptText = buildScriptHeader(summary) + scriptContent.trim() + "\n";
  const updatedAt = new Date().toISOString();

  const preview = scriptContent.trim().substring(0, 500);
  console.log(
    "[AI Action] Writing script (" + scriptContent.trim().length + " chars):\n" +
    preview + (scriptContent.trim().length > 500 ? "\n..." : "")
  );

  fs.writeFileSync(paths.scriptPath, scriptText, "utf8");
  fs.writeFileSync(
    paths.metaPath,
    JSON.stringify({ summary, updatedAt }, null, 2),
    "utf8"
  );

  return {
    scriptPath: paths.scriptPath,
    metaPath: paths.metaPath,
    summary,
    updatedAt,
  };
}

export async function runAiAction(projectRoot?: string) {
  if (!hasAiAction(projectRoot)) {
    throw new Error("No AI Action is currently loaded.");
  }

  const paths = resolveAiActionPaths(projectRoot);
  if (!paths) {
    throw new Error("AI Action storage could not be resolved from the extension path.");
  }

  // Security guard: ensure the script path is inside the .session/ directory.
  // resolveAiActionPaths always builds this path, but we validate explicitly as
  // defense-in-depth in case the calling context changes in the future.
  const resolvedScript = path.resolve(paths.scriptPath);
  const resolvedDir = path.resolve(paths.actionDir);
  if (!resolvedScript.startsWith(resolvedDir + path.sep)) {
    throw new Error("AI Action path is outside the session directory.");
  }

  return await evalTS("runScriptFile", paths.scriptPath);
}
