#!/bin/bash
#
# create_panel.sh — Create an AE ScriptUI panel skeleton and symlink it.
#
# Usage: create_panel.sh <repo_root> <panel_name> [ae_version]
#
# Arguments:
#   repo_root   — Absolute path to the ae-ai-starter repo
#   panel_name  — Name for the panel (e.g. "My Tool")
#   ae_version  — AE version year (e.g. "2025"). Auto-detected if omitted.
#
# Creates:
#   Scripts/panel/<filename>.jsx  — Panel entry point
#   Symlink in AE's ScriptUI Panels folder pointing to the panel file
#

set -euo pipefail

REPO_ROOT="${1:?Usage: create_panel.sh <repo_root> <panel_name> [ae_version]}"
PANEL_NAME="${2:?Usage: create_panel.sh <repo_root> <panel_name> [ae_version]}"
AE_VERSION="${3:-}"

# --- Derive file name from panel name ---
FILENAME=$(echo "$PANEL_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | sed 's/[^a-z0-9_]//g')
if [ -z "$FILENAME" ]; then
  echo "ERROR: Panel name produced an empty filename." >&2
  exit 1
fi
FILENAME="${FILENAME}_panel.jsx"

# --- Validate repo root ---
if [ ! -d "$REPO_ROOT/Scripts" ]; then
  echo "ERROR: $REPO_ROOT/Scripts does not exist. Is this an ae-ai-starter repo?" >&2
  exit 1
fi

PANEL_DIR="$REPO_ROOT/Scripts/panel"
mkdir -p "$PANEL_DIR"

PANEL_FILE="$PANEL_DIR/$FILENAME"

# --- Check if panel file already exists ---
if [ -f "$PANEL_FILE" ]; then
  echo "ERROR: $PANEL_FILE already exists. Remove it first or choose a different name." >&2
  exit 1
fi

# --- Auto-detect AE version if not provided ---
if [ -z "$AE_VERSION" ]; then
  # Find the newest AE installation
  AE_VERSION=$(ls -1d /Applications/Adobe\ After\ Effects\ * 2>/dev/null \
    | sed 's|.*/Adobe After Effects ||' \
    | sort -rn \
    | head -1)
  if [ -z "$AE_VERSION" ]; then
    echo "ERROR: No After Effects installation found in /Applications." >&2
    echo "Install After Effects or pass the version year as the third argument." >&2
    exit 1
  fi
  echo "Auto-detected AE version: $AE_VERSION"
fi

AE_PANELS_DIR="/Applications/Adobe After Effects $AE_VERSION/Scripts/ScriptUI Panels"

if [ ! -d "$AE_PANELS_DIR" ]; then
  echo "ERROR: ScriptUI Panels folder not found at:" >&2
  echo "  $AE_PANELS_DIR" >&2
  echo "Check your AE installation or pass the correct version year." >&2
  exit 1
fi

# --- Write panel skeleton ---
cat > "$PANEL_FILE" << 'PANELEOF'
/**
 * {{FILENAME}}
 *
 * Dockable ScriptUI panel: {{PANEL_NAME}}
 * Generated by ae-add-ui-panel skill.
 *
 * Install: symlink into AE's ScriptUI Panels folder (done automatically).
 * All code is ES3/ExtendScript compatible.
 */

#include "../lib/helpers.jsxinc"
#include "../lib/io.jsxinc"

(function (thisObj) {
    var PANEL_TITLE = "{{PANEL_NAME}}";

    // --- Panel window setup ---
    var win;
    try {
        win = (thisObj instanceof Panel) ? thisObj :
            new Window("palette", PANEL_TITLE, undefined, { resizeable: true });
    } catch (_) {
        win = new Window("palette", PANEL_TITLE, undefined, { resizeable: true });
    }

    win.orientation = "column";
    win.alignChildren = ["fill", "top"];
    win.spacing = 8;
    win.margins = 12;

    // --- Status bar ---
    var statusText = win.add("statictext", undefined, "Ready");
    statusText.alignment = ["fill", "top"];

    function setStatus(msg) {
        statusText.text = msg;
    }

    // --- Helpers ---
    function getActiveComp() {
        if (!app.project) {
            throw new Error("No project open.");
        }
        if (!app.project.activeItem || !(app.project.activeItem instanceof CompItem)) {
            throw new Error("Select or open a composition first.");
        }
        return app.project.activeItem;
    }

    function runAction(label, fn) {
        try {
            app.beginUndoGroup(label);
            fn();
            app.endUndoGroup();
            setStatus(label + " — done");
        } catch (e) {
            try { app.endUndoGroup(); } catch (_) {}
            setStatus(label + " failed");
            alert(label + " failed.\n\n" + e.toString());
        }
    }

    // ================================================================
    // ADD YOUR PANEL SECTIONS AND BUTTONS BELOW
    // ================================================================

    var mainPanel = win.add("panel", undefined, "Actions");
    mainPanel.orientation = "column";
    mainPanel.alignChildren = ["fill", "top"];
    mainPanel.margins = 10;

    var exampleBtn = mainPanel.add("button", undefined, "Example Action");
    exampleBtn.onClick = function () {
        runAction("Example", function () {
            var comp = getActiveComp();
            alert("Active comp: " + comp.name + "\n" + comp.width + "x" + comp.height);
        });
    };

    // ================================================================

    win.onResizing = win.onResize = function () {
        this.layout.resize();
    };

    setStatus("Ready");

    if (win instanceof Window) {
        win.center();
        win.show();
    } else {
        win.layout.layout(true);
    }
})(this);
PANELEOF

# --- Replace placeholders ---
sed -i '' "s|{{FILENAME}}|$FILENAME|g" "$PANEL_FILE"
sed -i '' "s|{{PANEL_NAME}}|$PANEL_NAME|g" "$PANEL_FILE"

echo "Created panel: $PANEL_FILE"

# --- Create symlink ---
SYMLINK_PATH="$AE_PANELS_DIR/$FILENAME"

if [ -L "$SYMLINK_PATH" ]; then
  echo "Symlink already exists at $SYMLINK_PATH — removing old one."
  rm "$SYMLINK_PATH"
elif [ -f "$SYMLINK_PATH" ]; then
  echo "WARNING: A regular file (not symlink) exists at $SYMLINK_PATH." >&2
  echo "Remove it manually if you want to replace it." >&2
  exit 1
fi

ln -s "$PANEL_FILE" "$SYMLINK_PATH"
echo "Symlinked: $SYMLINK_PATH -> $PANEL_FILE"

echo ""
echo "Done! Restart After Effects, then open the panel from Window > $PANEL_NAME."
